# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([[2,4,5,6]], np.int64)

In [3]:
print(myarr)

[[2 4 5 6]]


In [4]:
myarr[0,0]

2

In [5]:
myarr[0,1]

4

In [6]:
myarr

array([[2, 4, 5, 6]], dtype=int64)

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
myarr[0,1]

4

In [10]:
myarr[0,1] = 45

In [11]:
myarr[0,1]

45

In [12]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
listarray.dtype

dtype('int32')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
zeros=np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
range=np.arange(15)

In [22]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,10,10)

In [24]:
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
empy=np.empty((4,6))

In [26]:
empy

array([[4.67296746e-307, 1.69121096e-306, 1.20161118e-306,
        7.56587585e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613040e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [27]:
emp_like=np.empty_like(lspace)

In [28]:
emp_like

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
ide=np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
ide.shape

(45, 45)

In [32]:
ide.size

2025

In [33]:
ide.dtype

dtype('float64')

In [34]:
arry=np.arange(99)

In [35]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [1]:
arry.reshape(3,33)
#3 rows with 33 members or element

NameError: name 'arry' is not defined

In [37]:
arry.reshape(1,99)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98]])

In [38]:
arry.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arry.shape

(99,)

In [49]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [50]:
arr = np.array(x)

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr.sum(axis=0)

array([12, 15, 18])

In [53]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [54]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
arr.flat

In [61]:
for item in arr.flat:
    print(item)


1
2
3
4
5
6
7
8
9


In [62]:
arr.ndim

2

In [63]:
arr.size

9

In [64]:
arr.nbytes

36

In [79]:
one =np.array([3,65,34,8,33])

In [80]:
one.argmax()

1

In [81]:
one.argmin()

0

In [82]:
one.argsort()

array([0, 3, 4, 2, 1], dtype=int64)

In [83]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr.argmax()

8

In [85]:
arr.argmin()

0

In [87]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [88]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [89]:
arr.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [90]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [91]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [92]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [93]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
arr2 = np.array([[1,2,3],
                [1,2,3],
                [1,2,3]])


In [112]:
arr+arr2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [113]:
arr*arr2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [114]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [116]:
arr2.sum()

18

In [117]:
arr2.max()

3

In [118]:
arr2.min()

1

In [119]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
np.where(arr<2)

(array([0], dtype=int64), array([0], dtype=int64))

In [124]:
np.count_nonzero(arr)

9

In [125]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))