In [1]:
import numpy as np

In [7]:
#Single Dimention Array
myarr=np.array([2,3,4,5])

In [8]:
myarr

array([2, 3, 4, 5])

In [9]:
print(myarr)

[2 3 4 5]


In [11]:
myarr[0]
mrarr[1]

2

In [13]:
# Multidimentional Array
my_arr=np.array([[2,3,4,5]])

In [14]:
print(my_arr)

[[2 3 4 5]]


In [15]:
my_arr

array([[2, 3, 4, 5]])

In [16]:
my_arr[0]

array([2, 3, 4, 5])

In [17]:
my_arr[0,0]

2

In [19]:
listarr=np.array([[1,2,3],[15,5,5],[5,3,1]])
listarr

array([[ 1,  2,  3],
       [15,  5,  5],
       [ 5,  3,  1]])

In [20]:
print(listarr)

[[ 1  2  3]
 [15  5  5]
 [ 5  3  1]]


In [21]:
listarr.dtype

dtype('int32')

In [22]:
listarr.shape

(3, 3)

In [23]:
listarr.size

9

In [28]:
range = np.arange(12)

In [26]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arry=np.arange(99)

In [30]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arry.reshape(3,33)
# Three rows 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arry.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arry.shape

(99,)

In [42]:
arrr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arrr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
print(arrr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
arrr.sum(axis=0)

array([12, 15, 18])

In [47]:
arrr.sum(axis=1)

array([ 6, 15, 24])

In [49]:
arrr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
arrr.flat

In [54]:
for item in arrr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [58]:
arrr.nbytes

36